version: "3.8"

services:

  accounts:
    image: zicovh/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - zicobank-network
    
  loans:
    image: zicovh/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - zicobank-network
    
  cards:
    image: zicovh/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - zicobank-network
    
networks:
  zicobank-network: